---
- hosts: 192.168.0.178
  gather_facts: false

  tasks:
    - name: Show running configuration
      ios_command:
        commands:
          - show running-config
      register: config

    - name: Save output to file
      copy:
        content: "{{config.stdout[0]}}"
        dest: "outputs/{{inventory_hostname}}-config.txt"
...
